[package]
name = "solana-rpc-core"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/solana-core"
readme = "../README.md"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[badges]
codecov = { repository = "solana-labs/solana", branch = "master", service = "github" }

[dependencies]
#base64 = { workspace = true }
#bincode = { workspace = true }
#bs58 = { workspace = true }
#chrono = { workspace = true, features = ["default", "serde"] }
crossbeam-channel = { workspace = true }
#dashmap = { workspace = true, features = ["rayon", "raw-api"] }
#eager = { workspace = true }
#etcd-client = { workspace = true, features = ["tls"] }
#histogram = { workspace = true }
#itertools = { workspace = true }
#lazy_static = { workspace = true }
log = { workspace = true }
#lru = { workspace = true }
#min-max-heap = { workspace = true }
num_enum = { workspace = true }
#rand = { workspace = true }
#rand_chacha = { workspace = true }
rayon = { workspace = true }
#rolling-file = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
solana-metrics = { workspace = true }
solana-net-utils = { workspace = true }
solana-rpc = { workspace = true }
solana-sdk = { workspace = true }
solana-version = { workspace = true }
#strum = { workspace = true, features = ["derive"] }
#strum_macros = { workspace = true }
sys-info = { workspace = true }
#tempfile = { workspace = true }
thiserror = { workspace = true }
#tokio = { version = "~1.14.1", features = ["full"] }
#trees = { workspace = true }

[dev-dependencies]
#fs_extra = { workspace = true }
matches = { workspace = true }
#raptorq = { workspace = true }
#serde_json = { workspace = true }
#serial_test = { workspace = true }
#solana-logger = { workspace = true }
#static_assertions = { workspace = true }
#systemstat = { workspace = true }
#test-case = { workspace = true }

[target."cfg(unix)".dependencies]
sysctl = { workspace = true }

[build-dependencies]
rustc_version = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
