[package]
name = "solana-storage-bigtable"
description = "Solana Storage BigTable"
documentation = "https://docs.rs/solana-storage-bigtable"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
async-trait = { workspace = true }
backoff = { workspace = true, features = ["tokio"] }
bincode = { workspace = true }
bytes = { workspace = true }
bzip2 = { workspace = true }
enum-iterator = { workspace = true }
flate2 = { workspace = true }
futures = { workspace = true }
goauth = { workspace = true }
http = { workspace = true }
hyper = { workspace = true }
hyper-proxy = { workspace = true }
log = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
smpl_jwt = { workspace = true }
solana-storage-adapter = { workspace = true }
solana-storage-proto = { workspace = true }
solana-transaction-status = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true, features = ["tls", "transport"] }
zstd = { workspace = true }

solana-clock = { workspace = true }
solana-pubkey = { workspace = true }
solana-signature = { workspace = true }
solana-sysvar = { workspace = true }
solana-time-utils = { workspace = true }
solana-transaction-status-client-types = { workspace = true }
solana-reserved-account-keys = { workspace = true }

# openssl is a dependency of the goauth and smpl_jwt crates, but explicitly
# declare it here as well to activate the "vendored" feature that builds OpenSSL
# statically...
[target."cfg(not(windows))".dependencies]
openssl = { workspace = true, features = ["vendored"] }
# ...except on Windows to avoid having to deal with getting CI past a build-time
# Perl dependency
[target."cfg(windows)".dependencies]
openssl = { workspace = true, features = [] }

[lib]
crate-type = ["lib"]
name = "solana_storage_bigtable"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
